# Generated by Django 5.1.1 on 2024-09-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=20)),
                ('heading', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='D:\\study\\Languages\\Django\\Django_project\\project_with_harry\x07pp_1\\static\x07pp_1\x07ssets\\img\\portfolio')),
            ],
        ),
    ]
