# Generated by Django 5.1.1 on 2024-09-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='D:\\study\\Languages\\Django\\Django_project\\project_with_harry'),
        ),
    ]
