# Generated by Django 5.1.1 on 2024-09-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_alter_portfolio_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_heading', models.CharField(max_length=70)),
                ('nav_item1', models.CharField(max_length=10)),
                ('nav_item2', models.CharField(max_length=10)),
            ],
        ),
    ]
