# Generated by Django 5.1.1 on 2024-10-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0005_navbar'),
    ]

    operations = [
        migrations.CreateModel(
            name='marks_sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('marks', models.IntegerField(default=0)),
            ],
        ),
    ]
