# Generated by Django 5.1.1 on 2024-11-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0007_binaryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binaryimage',
            name='title',
        ),
        migrations.AddField(
            model_name='binaryimage',
            name='group_name',
            field=models.CharField(default='default_group', max_length=100),
        ),
    ]
