# Generated by Django 5.1.1 on 2024-11-28 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0010_remove_binaryimage_group_name_binaryimage_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='binaryimage',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='binaryimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
