# Generated by Django 5.1.1 on 2024-11-18 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0003_rename_user2_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
