# Generated by Django 5.1.1 on 2024-11-18 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0005_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
