# Generated by Django 5.1.1 on 2024-11-18 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0006_image_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
