# Generated by Django 5.1.1 on 2024-11-21 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0010_image2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image2',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
