# Generated by Django 5.1.1 on 2024-11-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0012_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='post_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
